"""crear tabla items solicitados

Revision ID: 63dd132e8e50
Revises: cd42cd5d5bea
Create Date: 2026-09-18 15:33:13.252051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63dd132e8e50'
down_revision: Union[str, Sequence[str], None] = 'cd42cd5d5bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_solicitados',
    sa.Column('id_item', sa.Uuid(), nullable=False),
    sa.Column('id_lead', sa.Uuid(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_al_momento', sa.Numeric(), nullable=True),
    sa.Column('existencias_al_momento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_lead'], ['leads.id_lead'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_solicitados')
    # ### end Alembic commands ###
