"""crear tabla evaluaciones motor

Revision ID: 888452505e07
Revises: 63dd132e8e50
Create Date: 2026-09-18 15:34:04.888730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '888452505e07'
down_revision: Union[str, Sequence[str], None] = '63dd132e8e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluaciones_motor',
    sa.Column('id_evaluacion', sa.Uuid(), nullable=False),
    sa.Column('id_lead', sa.Uuid(), nullable=False),
    sa.Column('id_mensaje', sa.Uuid(), nullable=False),
    sa.Column('monto_estimado', sa.Numeric(), nullable=True),
    sa.Column('relacion_cliente', sa.Float(), nullable=True),
    sa.Column('completitud', sa.Float(), nullable=True),
    sa.Column('plazo_dias', sa.Integer(), nullable=True),
    sa.Column('prioridad', sa.Float(), nullable=True),
    sa.Column('nivel_prioridad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reglas_activadas', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_lead'], ['leads.id_lead'], ),
    sa.ForeignKeyConstraint(['id_mensaje'], ['mensajes.id_mensaje'], ),
    sa.PrimaryKeyConstraint('id_evaluacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluaciones_motor')
    # ### end Alembic commands ###
