"""agregar_telefono_a_conversaciones

Revision ID: c32109910bee
Revises: 888452505e07
Create Date: 2026-09-26 04:02:03.146979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c32109910bee'
down_revision: Union[str, Sequence[str], None] = '888452505e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversaciones', sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversaciones', 'telefono')
    # ### end Alembic commands ###
