"""agregar prioridad escalacion y cierre a leads

Revision ID: cd42cd5d5bea
Revises: c8d3e5f10a27
Create Date: 2026-09-18 15:31:56.769140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd42cd5d5bea'
down_revision: Union[str, Sequence[str], None] = 'c8d3e5f10a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('monto_estimado', sa.Numeric(), nullable=True))
    op.add_column('leads', sa.Column('fecha_requerida', sa.Date(), nullable=True))
    op.add_column('leads', sa.Column('prioridad', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('nivel_prioridad', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('leads', sa.Column('escalado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('leads', sa.Column('motivo_escalacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('leads', sa.Column('escalado_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('leads', 'productos_interes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('leads', 'ciudad',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_un_lead_abierto_por_conversacion', 'leads', ['id_conversacion'], unique=True, postgresql_where=sa.text("estado_lead = 'en_proceso'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_un_lead_abierto_por_conversacion', table_name='leads', postgresql_where=sa.text("estado_lead = 'en_proceso'"))
    op.alter_column('leads', 'ciudad',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('leads', 'productos_interes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('leads', 'cerrado_en')
    op.drop_column('leads', 'escalado_en')
    op.drop_column('leads', 'motivo_escalacion')
    op.drop_column('leads', 'escalado')
    op.drop_column('leads', 'nivel_prioridad')
    op.drop_column('leads', 'prioridad')
    op.drop_column('leads', 'fecha_requerida')
    op.drop_column('leads', 'monto_estimado')
    # ### end Alembic commands ###
